### ISSUE TITLE
Translated to PT/BR

### ISSUE THREAD

**Issue by El-SpaceX** [NexiusTailer/Ultimate-Creator#3]
I loved this editor, so I translated it to PT/BR, and posted it on some discord servers (with your credits obviously).

Translated version: https://github.com/El-SpaceX/Ultimate-Creator-PTBR

**Comment by NexiusTailer** [comment]
Great, thank you so much!
I could merge this version into the main repo so it'll be available from another folder like it's now with `/Russian` and `/English` paths. `README.md` can also be added as translated to the main repo, just will be renamed into `README_PT_BR.md` or in any other appropriate way.

**Comment by El-SpaceX** [comment]
I think it's a good idea.
Sorry for my bad english.

**Comment by NexiusTailer** [comment]
Ok, seems I managed it and I wanted to ask you to test it at first from the releases section where I just added your localization:
https://github.com/NexiusTailer/Ultimate-Creator/releases/tag/v1.4.5

Please click on & download PR-BR archive and check bare.pwn and creator.pwn if they still display all the symbols correctly (have the same encoding as before and works well for you in game). I ask this because I wanna know for sure if my own OS didn't messed anything in the files and will not in the future updates when I will make any changes to these files. Because having only En/Ru lang packs it sometimes displays other languages weird for me (like [that](https://imgur.com/a/SYwkgaP)).

If everything will be ok I'll add all remained files in the repo itself as well 😀

**Comment by El-SpaceX** [comment]
Everything is alright.  🤗

However, while I was analyzing it I noticed some errors in my writing(very few, but they can cause confusion) in the 'creator.pwn'.
I update in my repository: https://github.com/El-SpaceX/Ultimate-Creator-PTBR

**Comment by NexiusTailer** [comment]
Alright, I merged all the changes into the repository and updated Releases section. Thank you again!
Now you can delete or archive your [fork repo](https://github.com/El-SpaceX/Ultimate-Creator-PTBR) (go to Settings section and do what you consider better) and pull any future changes into this main repo so people could find it in all available languages in one place 🙂

I also added you to [Credits list](https://github.com/NexiusTailer/Ultimate-Creator#thanks) in readme, so, let me know if I should change something there or everything is correct now.
